# Generated by Django 5.2 on 2025-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='original_instruction',
            field=models.TextField(blank=True, help_text='La instrucción original del usuario si fue creado vía IA.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='original_instruction',
            field=models.TextField(blank=True, help_text='La instrucción original del usuario si fue creado vía IA.', null=True),
        ),
    ]
