# Generated by Django 5.2 on 2025-05-10 15:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(help_text='Usuario al que pertenece esta categoría', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descripción del gasto.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del gasto.', max_digits=10)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se realizó el gasto.')),
                ('type', models.CharField(choices=[('expense', 'Gasto')], default='expense', help_text='Tipo de transacción (actualmente solo Gasto).', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el gasto (opcional).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Categoría del gasto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.category')),
                ('project', models.ForeignKey(blank=True, help_text='Proyecto de TaskFlow al que está asociado este gasto (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.project')),
                ('user', models.ForeignKey(help_text='Usuario que registró el gasto.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
