# Generated by Django 5.2 on 2025-05-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_transaction_original_instruction_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('ARS', 'Argentine Peso'), ('USD', 'US Dollar')], default='ARS', help_text='Currency of the transaction.', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_usd',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate (ARS per 1 USD) if the original transaction was in USD.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in the original currency (e.g., ARS or USD).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount converted to ARS. If original was USD, this is original_amount * exchange_rate_usd.', max_digits=10),
        ),
    ]
